---
- hosts: webservers
  connection: ssh
  become: yes
  tasks:
 
    - name: Check if Git is installed
      command: which git
      register: git_check
      ignore_errors: yes
 
    - name: Install Git if not present
      apt:
        name: git
        state: present
      when: git_check.rc != 0
 
    - name: Check if Java is installed
      command: java -version
      register: java_check
      ignore_errors: yes
 
    - name: Install OpenJDK if not present
      apt:
        name: openjdk-11-jdk
        state: present
      when: java_check.rc != 0
 
    - name: Check if Python is installed
      command: which python3
      register: python_check
      ignore_errors: yes
 
    - name: Install Python3 if not present
      apt:
        name: python3
        state: present
      when: python_check.rc != 0